FROM node:15.10.0-alpine as builder

# deps
RUN apk add alpine-sdk cairo-dev pango-dev jpeg-dev

# file watcher
RUN npm i -g nodemon

# files
COPY . /data

WORKDIR /data

EXPOSE 8080

CMD ["nodemon"]
